# Generated by Django 5.2.8 on 2025-11-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('user_id', models.BigIntegerField()),
                ('channel_id', models.BigIntegerField()),
                ('location_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('location_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_type', models.CharField(blank=True, max_length=255, null=True)),
                ('truck_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='telegram_app.message')),
            ],
        ),
    ]
