# Generated by Django 5.2.8 on 2026-01-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0002_telegrammessage_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_tracked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
