# Generated by Django 5.2.8 on 2026-01-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_channel_is_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='telegram_app.message'),
        ),
    ]
